### ISSUE TITLE
Demos broken

### ISSUE THREAD

**Issue by crazy4groovy** [getify/a-tale-of-three-lists#3]
"A Parser-blocking, cross site (i.e. different eTLD+1) script, https://rawnpm.getify.io/asynquence/latest/asq.js, is invoked via document.write. The network request for this script MAY be blocked by the browser in this or a future page load due to poor network connectivity. If blocked in this page load, it will be confirmed in a subsequent console message. See https://www.chromestatus.com/feature/5718547946799104 for more details."

Status in Chromium

Enabled by default (launch bug) in:
Chrome for desktop release 55

**Comment by getify** [comment]
Thanks for the report. The "CDN" urls I was using were in fact broken (for a long time). I've updated those URLs now to use a different service. The demos now work again.

The specific warning you're mentioning is different, which is that they're warning that my use of `document.write(..)` for the online demos is potentially a problem if Chrome decides that someone is on a slow connection and `document.write(..)` will then block network requests.

Unfortunately, without using a more complex build process which would burden future users of this repo, the `document.write(..)` is the only way I've found to let people run the demos either locally or online, with the same unaltered code.

Anyway, the demos now should work. Thanks.
